### PR TITLE
add KingSuper gentx and peer

### PR DESCRIPTION
**Pull request by aditya-manit**

### CODE REVIEW

**Comment by avkr003** [comment]
Please resubmit genesis tx. 0% commission rate is not allowed.

**Review by avkr003 — CHANGES_REQUESTED** [review]
Please resubmit genesis tx. 0% commission rate is not allowed.

**Comment by aditya-manit** [comment]
hey @avkr003 is there any minimum as such ? that I can set ?

**Comment by aditya-manit** [comment]
@avkr003 please check now

**Review by deepanshutr — APPROVED** [review]
This PR is validated and the gentx is accepted to be included in genesis of mantle-1 chain. Please ensure that the `mantleNode version` command results in output `HEAD-5b2b0dcb37b107b0e0c1eaf9e907aa9f1a1992d9`, if not then please delete the repo and checkout the tag v0.3.0 again and rebuild.

**Review by avkr003 — APPROVED** [review]

**Comment by aditya-manit** [comment]
Sure @deepanshutr 
I am on the right version
```
mantleNode version
HEAD-5b2b0dcb37b107b0e0c1eaf9e907aa9f1a1992d9
```

**Pull request merged**
