### PR TITLE
add gentx-KURASH.json && peers-KURASH.json

### PR DESCRIPTION
**Pull request by kuraassh**
Previously, I filled out a form on the mainnet validator, now I send a gentx transaction and add my future peer (if they take me to genesis)

### CODE REVIEW

**Comment by nk307** [comment]
This PR is rejected due to a suspicious/unverified request. Requesting you to kindly resubmit the same with justification to prevent malicious activity.

**Comment by kuraassh** [comment]
Can you please tell me what is wrong with the pull request?  I updated the binary file on the server, do I need to recreate the genth for the pull request?

**Comment by nk307** [comment]
Can you please follow the exact steps as provided in the doc and raise PR again with the latest changes?

**Comment by kuraassh** [comment]
Sure, thanks for the comment.  I will do it now!

**Comment by kuraassh** [comment]
ready - https://github.com/AssetMantle/genesisTransactions/pull/128

**Pull request closed without merging**
